### ISSUE TITLE
`decode` should use an anonymous generic for the string

### ISSUE THREAD

**Issue by Alexandcoats** [iotaledger/common-rs#64]
## Description

The most common use-case for this function is it call it like so:

```rust
let bytes = prefix_hex::decode::<Vec<u8>>(&hex_str)?;
```

But with the recent changes, the generic `S: AsRef<str>` must also be specified.

```rust
let bytes = prefix_hex::decode::<Vec<u8>, _>(&hex_str)?;
```

This parameter should be inferred for usability.

```rust
pub fn decode<T: FromHexPrefixed>(hex: impl AsRef<str>) -> Result<T, Error> {
    T::from_hex_prefixed(hex)
}
```

Also, this change was breaking but was not marked as such in the changelog.

**Comment by Alexandcoats** [comment]
That's fair. Still, it's nice to have a heads up.

**Comment by thibault-martinez** [comment]
> That's fair. Still, it's nice to have a heads up.

Definitely, sorry about that.
